name: Python Calculator UI CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-ui-app:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk

      - name: Lint code
        run: |
          pip install flake8
          flake8 calculator_ui.py

      - name: Build Docker Image
        run: |
          docker build -t python-calculator-ui .

      - name: (Optional) Run GUI app inside Docker
        run: |
          echo "Skipping GUI test in CI — requires display server"
